---
- name: Update system packages and install Apache + PHP
  hosts: all
  become: true

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Apache and PHP packages
      apt:
        name: 
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted

...